name: Use-IPYNB
on:
  push:
    branches:
    - main
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "设置虚拟环境"
        run: |
          sudo rm -rf /usr/bin/conda
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -n ip python=3.8 pip ipython 
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate ip
          pip install nbformat
      - name: 安装 GitHub 监控平台
        run: |
          sudo apt-get install netdata -y &>/dev/null && echo "监测平台安装成功." || echo "安装失败，请检查网络连接或更新apt cache"
          sudo netdata -d -i 127.0.0.1 -p 8089
          curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz | sudo tar zx -C /usr/bin
          nohup bore local 8089 --to bore.pub &
          exit
          sleep 5
    
      - name: 启动阶段I
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate ip
          sudo bash -c "echo 3 > /proc/sys/vm/drop_caches" 
          ipython -c "%run 1.delete_all_java_runtime.ipynb"
          ipython -c "%run 2.check_java_version.ipynb"
          ipython -c "%run 3.create_server.ipynb"

      - name: 创建一个tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TOKEN }}

      - name: 启动阶段II
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate ip
          ipython -c "%run 4.start_serverI.ipynb"
          ipython -c "%run 5.allow_eula.ipynb"
          ipython -c "%run 6.start_serverII.ipynb"
          echo succeed.
          exit
