name: Play-Minecraft-On-Action
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 安装 GitHub 监测平台
        run: |
          sudo apt-get install netdata -y &>/dev/null && echo "监测平台安装成功." || echo "安装失败，请检查网络连接或更新apt cache"
          sudo netdata -d -i 127.0.0.1 -p 8089
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x cloudflared-linux-amd64
          nohup ./cloudflared-linux-amd64 tunnel --url 127.0.0.1:8089 &
          exit
          sleep 10 && cat nohup.out
          echo =+=+=+=+=+=+=+=+=+=+=+=+成功安装服务，地址如下+=+=+=+=+=+=+=+=+=+=+=+=          
          
      - name: 安装Minecraft依赖
        run: |
          sudo apt update &>/dev/null && echo "apt cache 成功更新." || echo "apt cache更新失败,您可能会受到没有更新的安装包文件."
          sudo apt-get install openjdk-17-jre-headless &>/dev/null && echo "好耶! Openjdk17 已经被成功安装." || echo "OpenJdk17安装失败."
          python check_java_version.py
      - name: 创建server服务
        run: |
          pip install runipy
          runipy create_server.ipynb
      - name: 自动Eula
        run: |
          cd /home/runner/work/Minecraft-Java--On-Action/Minecraft-Java--On-Action/Minecraft-Server/
          sed -i '$d' eula.txt
          cat eula.txt
          echo "eula=true" >> eula.txt
      - name: 启动server 
        run: |
          cd /home/runner/work/Minecraft-Java--On-Action/Minecraft-Java--On-Action/
          runipy start_server.ipynb
