name: Play-Minecraft-On-Action
on: 
  #push:
  #  branches:
  #  - main
    
  workflow_dispatch:
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: read
      actions: read

    steps:
      - uses: actions/checkout@v3
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TOKEN }}
          
      - name: 获取最新tag
        id: get_version
        run: |
          echo ::set-output name=VERSION:: $(wget --no-check-certificate -qO- https://api.github.com/repos/lemonfan-maker/minecraft-java-on-action/tags | grep 'name' | cut -d\" -f4 | head -1)
          echo ${{ steps.get_version.outputs.VERSION }}

      #- name: 设置虚拟环境
      #  run: |
      #    sudo rm -rf /usr/bin/conda
      #    export PATH="/usr/share/miniconda/bin:$PATH"
      #    conda create -n j-n python=3.8 jupyter notebook
      #    
      #- name: 安装 GitHub 监控平台
        # run: |
          # sudo sysctl -w net.core.rmem_max=2500000
          # sudo apt-get install netdata -y &>/dev/null && echo "监测平台安装成功." || echo "安装失败，请检查网络连接或更新apt cache"
          # sudo netdata -d -i 127.0.0.1 -p 8089
          # curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz | sudo tar zx -C /usr/bin
          # nohup bore local 8089 --to bore.pub &
          # exit
          
      # - name: 运行Jupyter Notebook
        # run: |
          # export PATH="/usr/share/miniconda/bin:$PATH"
          # source activate j-n
          # jupyter notebook --generate-config
          # rm -rf /home/runner/.jupyter/jupyter_notebook_config.py
          # cp jupyter_notebook_config.py /home/runner/.jupyter/
          # sudo bash -c "echo 3 > /proc/sys/vm/drop_caches"
          # jupyter notebook &
          # nohup bore local 8837 --to bore.pub &
          # sleep 5m
          # exit

      # - name: 保存
        # run: |
          # tar -cvpzf Minecraft-Server.tgz Minecraft-Server
          
      #- name: 上传
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    tag_name: 
      #    name: Minecraft-Server
      #    body: Download File
      #    draft: false
      #    prerelease: false
      #    files: /home/runner/work/Minecraft-Java-On-Action/Minecraft-Java-On-Action/Minecraft-Server.tgz
