name: Play-Minecraft-On-Action
on:    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TOKEN }}
          
      - name: "设置虚拟环境"
        run: |
          sudo rm -rf /usr/bin/conda
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -n j-n python=3.8 jupyter pip notebook jupyterlab
      - name: 安装 GitHub 监控平台
        run: |
          sudo apt-get install netdata -y &>/dev/null && echo "监测平台安装成功." || echo "安装失败，请检查网络连接或更新apt cache"
          sudo netdata -d -i 127.0.0.1 -p 8089
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 > /dev/null
          chmod a+x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared
          nohup ./cloudflared tunnel --url 127.0.0.1:8089 &
          cat nohup.out
          exit

     # - name: 运行Jupyter Notebook
     #   run: |
     #     export PATH="/usr/share/miniconda/bin:$PATH"
     #     source activate j-n
     #     jupyter notebook --generate-config
     #     rm -rf /home/runner/.jupyter/jupyter_notebook_config.py
     #     cp jupyter_notebook_config.py /home/runner/.jupyter/
     #     sudo bash -c "echo 3 > /proc/sys/vm/drop_caches"
     #     jupyter notebook &
     #     bore local 8837 --to bore.pub

