name: Play-Minecraft-On-Action
on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "设置虚拟环境"
        run: |
          sudo rm -rf /usr/bin/conda
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -n j-n python=3.8 jupyter pip notebook
      - name: 安装 GitHub 监控平台
        run: |
          sudo apt-get install netdata -y &>/dev/null && echo "监测平台安装成功." || echo "安装失败，请检查网络连接或更新apt cache"
          sudo netdata -d -i 127.0.0.1 -p 8089
          curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz | sudo tar zx -C /usr/bin
          nohup bore local 8089 --to bore.pub &
          exit
          sleep 5
          echo =+=+=+=+=+=+=+=+=+=+=+=+成功安装服务，地址如下+=+=+=+=+=+=+=+=+=+=+=+=          
          cat nohup.out | grep bore.pub
    
      - name: 启动在线jupyter笔记本
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate j-n
          jupyter notebook --generate-config
          rm -rf /home/runner/.jupyter/jupyter_notebook_config.py
          cp jupyter_notebook_config.py /home/runner/.jupyter/
          sudo bash -c "echo 3 > /proc/sys/vm/drop_caches" 
          jupyter notebook &
          curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz | sudo tar zx -C /usr/bin 
          bore local 8837 --to bore.pub
          sleep 30m
          exit
      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.1.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          file-path: /home/runner/work/Minecraft-Java-On-Action/Minecraft-Java-On-Action/Minecraft-Server/
          owner: LemonFan-maker
          repo: Minecraft-Java-On-Action
