name: Play-Minecraft-On-Action
on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 安装 GitHub 监测平台
        run: |
          sudo apt-get install netdata -y &>/dev/null && echo "监测平台安装成功." || echo "安装失败，请检查网络连接或更新apt cache"
          sudo netdata -d -i 127.0.0.1 -p 8089
          curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz | sudo tar zx -C /usr/bin
          nohup bore local 8089 --to bore.pub &
          exit
          sleep 5
          echo =+=+=+=+=+=+=+=+=+=+=+=+成功安装服务，地址如下+=+=+=+=+=+=+=+=+=+=+=+=          
          cat nohup.out | grep bore.pub
          
      - name: 启动在线jupyter笔记本
        run: |
          pip install jupyter
          python -m pip install ipykernel -U --force-reinstall
          pip install ipython
          pip install notebook
          pip uninstall markupsafe --y
          pip install markupsafe==2.0.1
          jupyter notebook --allow-root --no-browser --port 6001 &
          curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz | sudo tar zx -C /usr/bin
          nohup bore local 6001 --to bore.pub &
