name: Play-Minecraft-On-Action
on:  
  workflow_dispatch:
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: read
      actions: read

    steps:
      - uses: actions/checkout@v3
      
      - name: 准备
        run: |
          cd /home/runner/work/Minecraft-Java-On-Action/
          aria2c https://github.com/cloudflare/cloudflared/releases/download/2022.11.1/cloudflared-fips-linux-amd64.deb > /dev/null
          sudo dpkg -i cloudflared-fips-linux-amd64.deb
      
      - name: 设置虚拟环境
        run: |
          sudo rm -rf /usr/bin/conda
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -n j-n python=3.8 jupyter notebook ipywidgets > /dev/null

      - name: 安装 GitHub 监控平台
        run: |
          sudo sysctl -w net.core.rmem_max=2500000
          sudo apt-get install netdata -y &>/dev/null && echo "监测平台安装成功." || echo "安装失败，请检查网络连接或更新apt cache"
          sudo netdata -d -i 127.0.0.1 -p 8089
          curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz | sudo tar zx -C /usr/bin
          nohup bore local 8089 --to bore.pub &
          exit
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - name: 运行Jupyter Notebook
        run: |
          cd /home/runner/work/Minecraft-Java-On-Action/Minecraft-Java-On-Action/
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate j-n
          jupyter notebook --generate-config
          rm -rf /home/runner/.jupyter/jupyter_notebook_config.py
          cp jupyter_notebook_config.py /home/runner/.jupyter/
          sudo bash -c "echo 3 > /proc/sys/vm/drop_caches"
          jupyter nbextension enable --py widgetsnbextension --sys-prefix
          jupyter notebook &
          nohup bore local 8837 --to bore.pub &
          sleep 15m
          exit

      - name: 保存
        run: |
          sleep 30s
          tar -cvpzf Minecraft-Server.tgz Minecraft-Server > /dev/null
          
      - name: 上传
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.1
          name: Minecraft-Server-v0.0.1
          files: /home/runner/work/Minecraft-Java-On-Action/Minecraft-Java-On-Action/Minecraft-Server.tgz