name: Play-Minecraft-On-Action
on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 安装 GitHub 监测平台
        run: |
          sudo apt-get install netdata -y &>/dev/null && echo "监测平台安装成功." || echo "安装失败，请检查网络连接或更新apt cache"
          sudo netdata -d -i 127.0.0.1 -p 8089
          curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz | sudo tar zx -C /usr/bin
          nohup bore local 8089 --to bore.pub &
          exit
          sleep 5
          echo =+=+=+=+=+=+=+=+=+=+=+=+成功安装服务，地址如下+=+=+=+=+=+=+=+=+=+=+=+=          
          cat nohup.out | grep bore.pub
          
      - name: 安装Minecraft依赖
        run: |
          pip install jupyter
          python -m pip install ipykernel -U --force-reinstall
          pip install ipython
          pip install notebook
          ipython --version
          sudo apt update &>/dev/null && echo "apt cache 成功更新." || echo "apt cache更新失败,您可能会受到没有更新的安装包文件."
          sudo apt-get install openjdk-17-jre-headless &>/dev/null && echo "好耶! Openjdk17 已经被成功安装." || echo "OpenJdk17安装失败."
          jupyter nbconvert --to notebook --execute check_java_version.ipynb --output check_java_version.ipynb
      - name: 创建server服务
        run: |
          runipy create_server.ipynb
      - name: 自动Eula
        run: |
          cd /home/runner/work/Minecraft-Java--On-Action/Minecraft-Java--On-Action/Minecraft-Server/
          sed -i '$d' eula.txt
          cat eula.txt
          echo "eula=true" >> eula.txt
      - name: 启动server 
        run: |
          cd /home/runner/work/Minecraft-Java--On-Action/Minecraft-Java--On-Action/
          runipy start_server.ipynb
